FROM rust as builder
RUN apt-get update && apt-get install -y && apt install git -y
RUN git clone https://github.com/vcd2df/rs_ex.git
RUN cargo install --path rs_ex

FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/cd-public/hasp25.git
COPY --from=builder /usr/local/cargo/bin/rs_ex /usr/local/bin/rs_ex
CMD ["rs_ex"]
